// Anything that doesn't interact with the dom

/**
 * @param {string} theme
 */
const setCurrentTheme = theme => {
	chrome.storage.local.set({ theme }).then(() => {
		console.log("Theme set successfully")
	})
}

/**
 * Get the current theme from storage
 * @returns {string} theme
 */

const getCurrentTheme = async () => {
	let theme
	await chrome.storage.local.get(["theme"]).then(result => {
		theme = result.theme
	})

	return theme
}

/**
 * @typedef {Object} VerseOfTheDay
 * @property {string} bibleReference
 * @property {string} bibleVerse
 *
 * @returns {VerseOfTheDay}
 */
const getVerse = async () => {
	let bibleVerse
	let bibleReference

	const currentDate = new Date()
	const day = currentDate.getDate()
	const month = currentDate.getMonth()
	const monthString = MONTHS[month]

	const dayStringIndex = `${monthString} ${day}`

	/**
	 * verses.json was generated by ChatGPT
	 */
	await fetch("./verses.json")
		.then(res => res.json())
		.then(data => {
			const verseOfTheDay = data[dayStringIndex]?.split("-")
			bibleVerse = verseOfTheDay[0]
			bibleReference = verseOfTheDay[1]
		})
	return { bibleVerse, bibleReference }
}

/**
 * Get today's date
 * @returns {string} today's date in form: Monday 16 October, 2023
 */
const getTodaysDate = () => {
	const today = new Date()
	const dateString = today.toDateString()
	return dateString
}

const MONTHS = [
	"January",
	"February",
	"March",
	"April",
	"May",
	"June",
	"July",
	"August",
	"September",
	"October",
	"November",
	"December",
]
